@startuml Телеграмм бот

component TelegramBot as Tb

left to right direction

package "Django"{
    component Model as model
    component View as view
}
 

database "PostgreSQL"{
    'component Data as data
    component MainChapters as MC
    component Subchupters as SC
}



Tb -down- view
view -down- model
model -down- chapters
chapters -down- MC
model -down- data
data -down- SC

@enduml